EXPERIMENT:
  NAME: ""
  TAG: "MLD,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "KD_ours"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
  LS: True
  EA: 1
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 480
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "ours"
KD:
  TEMPERATURE: 2
  LOSS:
    KD_WEIGHT: 4.0










































